### ISSUE TITLE
Good practices

### ISSUE THREAD

**Issue by edysegura** [MarceloBorgesP/PayCheck-Calculator#1]
Hi @MarceloBorgesP!

It is a good practice to inform with `console.log()` which port the application is up and running.

https://github.com/MarceloBorgesP/PayCheck-Calculator/blob/master/server.js#L21-L24

**Comment by MarceloBorgesP** [comment]
I had created a version 2.0 in another branch doing these things I hadn't
had time enough to do previously. My branch 2.0 is now merged with my exam
branch, you can check this and other nice improvements I did there now.

**Comment by MarceloBorgesP** [comment]
Hi @edysegura!

I had created a version 2.0 in another branch doing these things I hadn't
had time enough to do previously. My branch 2.0 is now merged with this branch
branch, you can check this and other nice improvements I did now.

I think everything is working as it should. Unfortunately I couldn't manage to do everything properly with the time available.

**Comment by MarceloBorgesP** [comment]
But look here for the improvements: https://github.com/univas-first-exam/marcelo-paycheck

This branch we are talking now is the wrong one. I created the project here, and then I moved to the univas-first-exam organization when I realized the mess I had done.

The project here is not up-to-date.
