### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by edysegura** [MarceloBorgesP/PayCheck-Calculator#2]
This application isn't doing the right calculation.

![image](https://cloud.githubusercontent.com/assets/5324414/10747693/4f5f2a48-7c3f-11e5-9939-310d8e7b34e1.png)

**Comment by MarceloBorgesP** [comment]
Fixed here:

https://github.com/univas-first-exam/marcelo-paycheck/

**Comment by edysegura** [comment]
Great!
