### ISSUE TITLE
Dev. Dependencies

### ISSUE THREAD

**Issue by edysegura** [MarceloBorgesP/PayCheck-Calculator#3]
Hi @MarceloBorgesP! 

We only use to add something to dev. dependencies tools and library related only to development, not the libraries that need to go in production.

https://github.com/MarceloBorgesP/PayCheck-Calculator/blob/master/package.json#L17

**Comment by MarceloBorgesP** [comment]
Fixed here:

https://github.com/univas-first-exam/marcelo-paycheck/blob/master/package.json#L16

**Comment by edysegura** [comment]
Awesome!
